spring:
  application:
    name: weekly-bulletin
  main:
    headless: false

bulletin:
  excel:
    path: ${BULLETIN_EXCEL_PATH:}
  logo:
    path: ${BULLETIN_LOGO_PATH:}
  illustration:
    folder: ${BULLETIN_ILLUSTRATIONS_PATH:}
  text:
    path: ${BULLETIN_TEXT_PATH:${user.home}/.church-management/text-config.properties}
  representative-prayer:
    path: ${BULLETIN_REPRESENTATIVE_PRAYER_PATH:${user.home}/.church-management/representative-prayer.json}

server:
  port: 8082
